### Conjunto de Ferramentas
## Conjunto
# Conjunto

In [29]:
import pandas as pd
import numpy as np

In [30]:
quantidade_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]

array_produtos = np.array(quantidade_produtos)
array_precos= np.array(precos_produtos)

faturamento = array_produtos * array_precos
print(faturamento)

[  30   25   42 1000]

In [31]:
quantidade_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]
nomes_produtos = ["Pastel","Caculinha","Refrigerante", "Combos"]
array_quantidade = np.array(quantidade_produtos)
array_produtos = np.array(precos_produtos)

faturamento = array_produtos * array_quantidade
for nome,preco in zip (nomes_produtos,faturamento):
    print (f"{nome} : {preco}")

Pastel : 30
Caculinha : 25
Refrigerante : 42
Combos : 1000

# Exercício de fixacao
- Criar uma lista que irá posuir 10 nomes de produtos
- lista que irá possuir o preco de custo (atacado)
- lista que irá possuir o preco de venda (varejo).
- Ao final exibir o lucro obtido em cada produto.

In [32]:
# 1 lista de produtos:

nomes_dos_produtos = ["Arroz", "Feijão", "Açúcar", "Café", "Óleo","Macarrão", "Leite", "Sal", "Farinha", "Manteiga"]

valor_custo = [15,4,1,15,7,2,3,2,3,3]
valor_venda = [25,8,2,30,14,4,6,4,6,6]

# Conversão para arrays
array_nomes_dos_produtos = np.array(nomes_dos_produtos)
array_custo = np.array(valor_custo)
array_venda = np.array(valor_venda)

# Cálculo do lucro (operação vetorizada)    
lucro = array_venda -array_custo
print(lucro)

print (np.sum(lucro))

#for nome,custo,venda in zip (array_nomes_dos_produtos,array_custo,array_venda):

[10  4  1 15  7  2  3  2  3  3]
50

###PANDAS

In [33]:
df.info ()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    str
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: float64(2), int64(1), str(4)
memory usage: 70.9 KB

In [34]:
df.isna()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
795,False,False,False,False,False,False,False
796,False,False,False,False,False,False,False
797,False,False,False,False,False,False,False
798,False,False,False,False,False,False,False
799,False,False,False,False,False,False,False

In [35]:
df.describe()

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000

In [36]:
df.columns

Index(['data_pedido', 'categoria', 'preco_unitario', 'quantidade', 'regiao',
       'canal_marketing', 'avaliacao'],
      dtype='str')

In [37]:
#Contar valores nulos

df.duplicated(). sum()

np.int64(0)

In [38]:
#dimensoes da tabela
df.shape

(800, 7)

In [39]:
#5 primeiros caminhos
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv") 
df.head()

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [40]:
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [41]:
df["classificacao_temperatura"] = np.where(df["temperatura_c"])>= 75, "Temperatura alta", "Temperatura baixa")
df.head

SyntaxError: unmatched ')' (1074764146.py, line 1)

##Techshop

In [ ]:
#5 primeiros caminhos
df1 = pd.read_csv(r".\Data\dataset_techshop_vendas.csv") 
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9

In [ ]:
df.isna().sum()

data_pedido        0
categoria          0
preco_unitario     0
quantidade         0
regiao             0
canal_marketing    0
avaliacao          0
dtype: int64

In [ ]:
#5 ultimos 
df.tail()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7

In [ ]:
#mostra o corpo 800 linhas e 7 colunas
print(df.shape)

(800, 7)

In [ ]:
#o preço médio ou se há algum produto com preço estranhamente alto (um possível outlier)
df.describe()

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    str
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: float64(2), int64(1), str(4)
memory usage: 70.9 KB

In [ ]:
df.describe()

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000

In [ ]:
df.isna().sum()

data_pedido        0
categoria          0
preco_unitario     0
quantidade         0
regiao             0
canal_marketing    0
avaliacao          0
dtype: int64

In [42]:
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [44]:
df.notnull().sum()

id_registro      40
setor            40
temperatura_c    40
tempo_ciclo_s    40
producao_dia     40
falha            40
dtype: int64

In [43]:
df["temperatura_c"]

0     72.62
1     81.65
2     68.87
3     66.84
4     66.23
5     64.79
6     85.02
7     60.31
8     75.84
9     68.38
10    76.31
11    74.79
12    76.31
13    63.28
14    64.98
15    81.48
16    79.62
17    69.80
18    77.16
19    73.30
20    79.77
21    71.76
22    74.16
23    74.69
24    74.03
25    75.96
26    60.80
27    69.37
28    70.28
29    73.53
30    63.59
31    68.91
32    77.62
33    73.32
34    78.24
35    68.47
36    75.62
37    78.50
38    76.19
39    68.64
Name: temperatura_c, dtype: float64

In [46]:
df[["id_registro","temperatura_c","falha"]]

    id_registro  temperatura_c  falha
0             1          72.62      0
1             2          81.65      0
2             3          68.87      0
3             4          66.84      0
4             5          66.23      0
5             6          64.79      0
6             7          85.02      1
7             8          60.31      0
8             9          75.84      0
9            10          68.38      1
10           11          76.31      0
11           12          74.79      0
12           13          76.31      0
13           14          63.28      0
14           15          64.98      0
15           16          81.48      0
16           17          79.62      1
17           18          69.80      0
18           19          77.16      0
19           20          73.30      1
20           21          79.77      0
21           22          71.76      0
22           23          74.16      0
23           24          74.69      1
24           25          74.03      1
25           26          75.96      0
26           27          60.80      0
27           28          69.37      1
28           29          70.28      0
29           30          73.53      0
30           31          63.59      1
31           32          68.91      0
32           33          77.62      1
33           34          73.32      1
34           35          78.24      0
35           36          68.47      0
36           37          75.62      1
37           38          78.50      0
38           39          76.19      1
39           40          68.64      0

In [47]:
df["classificacao_temperatura"] = np.where(df["temperatura_c"]>=75,"Temperatura Alta","Temperatura baixa")
df.head()

,id_registro,setor,temperatura_c,tempo_ciclo_s,producao_dia,falha,classificacao_temperatura
0,1,Montagem,72.62,41.77,111,0,Temperatura baixa
1,2,Usinagem,81.65,34.08,128,0,Temperatura Alta
2,3,Usinagem,68.87,39.44,159,0,Temperatura baixa
3,4,Usinagem,66.84,34.52,98,0,Temperatura baixa
4,5,Usinagem,66.23,31.57,94,0,Temperatura baixa